### ISSUE TITLE
Nano S displaying change address + change amount instead of receiving address with Mycelium and Electrum

### ISSUE THREAD

**Issue by Transisto** [LedgerHQ/ledger-nano-s#5] opened 2016-10-09 05:56 UTC
https://github.com/spesmilo/electrum/issues/1961#event-817265722

**Comment by Transisto** [comment] 2016-10-09 05:59
This bring me to ask, How is the change address verified ?

What if the change address (not displayed) is not one belonging to the Ledger wallet ?
Like what just happened...

**Comment by btchip** [comment] 2016-10-18 20:15
That bug was caused by an unfortunate bug in the HW.1 code conversion process. It is fixed in the new BTC application provided with firmware 1.2 (closing commit is https://github.com/LedgerHQ/blue-app-btc/commit/ba6f5a785dbff7fd5e16cfe72597948fe51a35c4)

**Closed as completed by btchip** 2016-10-18 20:15 UTC
